apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: sukrity/gitops01:60fd17ab1817d6f45af439f20e980f256cb22525
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        group: mem
