apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: sukrity/gitops01:210206aa41297d02c718885c1372a46e99737529
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        group: mem
